name: Memory jobs

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Corrupt JPG Check
        run: |
          for file in $(find . -type f -name "*.jpg"); do
            if ! file "$file" | grep -q "JPEG image data"; then
              echo "$file is corrupt. Replacement..."
              cp html/data/shrek.jpg "$file"
            else
              echo "$file is not corrupted."
            fi
          done

  build-memory:
    runs-on: self-hosted
    needs: test-memory

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ElvinAlb/memory .

  push-memory:
    runs-on: self-hosted
    needs: build-memory

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Verify Docker Login
        run: docker info

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/memory
